name: Setup Workspace
description: Checkout and install all dependencies

runs:
  using: composite
  steps:
  - uses: actions/setup-java@v5
    with:
      distribution: temurin
      java-version: 21
      cache: gradle
