version: 2.1

orbs:
  codecov: codecov/codecov@3

executors:
  linux:
    docker:
      - image: cimg/openjdk:21.0

jobs:
  verification:
    executor: linux
    steps:
      - checkout
      - run: ./gradlew check

workflows:
  build:
    jobs:
      - verification
