version: 2.1

executors:
  openjdk:
    docker:
      - image: cimg/openjdk:21.0
  renovate:
    docker:
      - image: renovate/renovate:latest

jobs:
  run-lint:
    executor: openjdk
    steps:
      - checkout
      - run: ./gradlew check
  activate-renovatebot:
    executor: renovate
    steps:
      - run: renovate

workflows:
  code-analysis:
    jobs:
      - run-lint
      - activate-renovatebot
