[versions]
kotlin = "1.9.10"
ktlint = "1.0.1"

[plugins]
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.7.4"
ktlint = "org.jlleitschuh.gradle.ktlint:11.6.1"
git-publish = "org.ajoberstar.git-publish:3.0.1" # max for jdk8
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# main
rulebook-ktlint = "com.hendraanggrian.rulebook:rulebook-ktlint:0.4"
# test
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
