version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3

executors:
  android:
    docker:
      - image: cimg/android:2026.03
  renovate:
    docker:
      - image: renovate/renovate:latest

jobs:
  setup-workspace:
    executor: android
    steps:
      - checkout
      - run: ./gradlew dependencies
      - persist_to_workspace:
          root: .
          paths: [.]
  run-lint:
    executor: android
    steps:
      - attach_workspace:
          at: .
      - run: ./gradlew ktlintCheck
  upload-coverage:
    executor: android
    steps:
      - attach_workspace:
          at: .
      - run: ./gradlew koverXmlReport
      - codecov/upload
  activate-renovatebot:
    executor: renovate
    steps:
      - run: renovate

workflows:
  code-analysis:
    jobs:
      - setup-workspace
      - run-lint:
          requires: [setup-workspace]
      - upload-coverage:
          requires: [setup-workspace]
      - activate-renovatebot
