[versions]
jdk = "21"
jre = "8"
sdk-min = "21"
sdk-target = "35"
kotlin = "2.0.0"
ktlint = "1.5.0"
android-plugin = "8.8.0"
androidx = "1.7.0"
androidx-test = "1.6.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.9.1"
ktlint = "org.jlleitschuh.gradle.ktlint:12.1.2"
maven-publish = "com.vanniktech.maven.publish.base:0.30.0"
git-publish = "org.ajoberstar.git-publish:5.1.0"
pages = "com.hanggrian.pages:0.1"

[libraries]
# lint
rulebook-ktlint = "com.hanggrian.rulebook:rulebook-ktlint:0.1"
# main
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.1"
material = { module = "com.google.android.material:material", version.ref = "androidx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-multidex = "androidx.multidex:multidex:2.0.1"
# test
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-junit = "androidx.test.ext:junit:1.2.1"
robolectric = "org.robolectric:robolectric:4.14.1"
truth = "com.google.truth:truth:1.4.4"

[bundles]
androidx-test = [
  "androidx-test-core", "androidx-test-runner", "androidx-test-junit",
  "robolectric", "truth"
]
