[versions]
jdk = "11"
kotlin = "1.7.20"
android-plugin = "7.3.1"
android-jdk = "8"
android-min = "14"
android-target = "32"
androidx = "1.5.0"
androidx-test = "1.4.0"

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-android-extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.6.1"
android-application = { id = "com.android.application", version.ref = "android-plugin" }
git-publish = "org.ajoberstar.git-publish:3.0.1"
pages = "com.hendraanggrian.pages:0.1"

[libraries]
# lint
ktlint = "com.pinterest:ktlint:0.47.1"
lints-ktlint = "com.hendraanggrian.lints:lints-ktlint:0.1-SNAPSHOT"
# main
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
material = { module = "com.google.android.material:material", version.ref = "androidx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-multidex = "androidx.multidex:multidex:2.0.1"
# test
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-junit = "androidx.test.ext:junit:1.1.3"
robolectric = "org.robolectric:robolectric:4.8.2"
truth = "com.google.truth:truth:1.1.3"

[bundles]
androidx-test = ["androidx-test-core", "androidx-test-runner", "androidx-test-junit", "robolectric", "truth"]
